### ISSUE TITLE
Property "fps" is deprecated.

### ISSUE THREAD

**Issue by lucasPV** [lvml/mpv-plugin-xrandr#10]
The property "fps" was renamed in the newer versions of mpv.
In line 228:
local f = mp.get_property_native("fps")
should be changed to
local f = mp.get_property_native("container-fps")
otherwise you will get 0hz.

**Comment by lvml** [comment]
Thanks for pointing this out - fixed.

**Comment by lucasPV** [comment]
Thanks!
