### ISSUE TITLE
Mirror Displays is enabled on playback.

### ISSUE THREAD

**Issue by emil-backstrand** [lvml/mpv-plugin-xrandr#13]
Hey! 

I've been using your script for awhile with much success, thank you for making it! 
Yesterday I changed the display in my Lenovo laptop from a 1600x900 to a FHD panel. 

Now, whenever I open a file my laptop screen is lit up and the picture is mirrored on both screens. 
I have tried diving into xrandr.lua but all I've learned is that I'm useless at coding. 

Here's the logs and attached xrandr -q output from before and after a movie is playing. 

### Before
![xrandr-qbefore](https://user-images.githubusercontent.com/44481350/47584694-916ea900-d95b-11e8-87b7-e4f65c92244f.png)
### After
![xrandr-qafter](https://user-images.githubusercontent.com/44481350/47584702-94699980-d95b-11e8-8a49-99d586ddcc92.png)
### mpv log
`/usr/bin/mpv --no-config --no-quiet --terminal --no-msg-color --input-file=/dev/stdin -v --no-fs --audio-spdif=ac3,dts-hd,truehd --vd-lavc-threads=4 --hwdec=vaapi --sub-auto=fuzzy --vo=gpu, --audio-device=pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo --ao=pulse, --no-input-default-bindings --input-vo-keyboard=no --no-input-cursor --cursor-autohide=no --no-keepaspect --wid=54525990 --monitorpixelaspect=1 --osd-level=0 --osd-scale=1 --osd-bar-align-y=0.6 --sub-ass --embeddedfonts --sub-ass-line-spacing=0 --sub-scale=1 --sub-font=Arial --sub-color=#ffffffff --sub-shadow-color=#ff000000 --sub-border-color=#ff000000 --sub-border-size=0.75 --sub-shadow-offset=2.5 --sub-font-size=50 --sub-bold=no --sub-italic=no --sub-codepage=ISO-8859-1 --sub-pos=100 --volume=40 --cache=99999 --screenshot-template=cap_%F_%p_%02n --screenshot-format=jpg --screenshot-directory=/tmp/smplayer_screenshots --volume-max=100 --video-output-levels=auto --profile=gpu-hq --vo=gpu --opengl-swapinterval=1 --video-sync=display-resample --audio-spdif=dts,ac3 --audio-channels=2 --ad=spdif:ac3,spdif:dts, --af=scaletempo,lavcac3enc=yes:640:3 --script ~/.config/mpv/scripts/xrandr.lua --term-playing-msg=MPV_VERSION=${=mpv-version:}
INFO_VIDEO_WIDTH=${=width}
INFO_VIDEO_HEIGHT=${=height}
INFO_VIDEO_ASPECT=${=video-aspect}
INFO_VIDEO_FPS=${=container-fps:${=fps}}
INFO_VIDEO_FORMAT=${=video-format}
INFO_VIDEO_CODEC=${=video-codec}
INFO_AUDIO_FORMAT=${=audio-codec-name}
INFO_AUDIO_CODEC=${=audio-codec}
INFO_AUDIO_RATE=${=audio-params/samplerate}
INFO_AUDIO_NCH=${=audio-params/channel-count}
INFO_LENGTH=${=duration:${=length}}
INFO_DEMUXER=${=current-demuxer:${=demuxer}}
INFO_SEEKABLE=${=seekable}
INFO_TITLES=${=disc-titles}
INFO_CHAPTERS=${=chapters}
INFO_TRACKS_COUNT=${=track-list/count}
METADATA_TITLE=${metadata/by-key/title:}
METADATA_ARTIST=${metadata/by-key/artist:}
METADATA_ALBUM=${metadata/by-key/album:}
METADATA_GENRE=${metadata/by-key/genre:}
METADATA_DATE=${metadata/by-key/date:}
METADATA_TRACK=${metadata/by-key/track:}
METADATA_COPYRIGHT=${metadata/by-key/copyright:}
INFO_MEDIA_TITLE=${=media-title:}
INFO_STREAM_PATH=${stream-path}
 --audio-client-name=SMPlayer --term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0} /home/emba/Movies/Quiet Place, A.mkv

Command line options: '--no-config' '--no-quiet' '--terminal' '--no-msg-color' '--input-file=/dev/stdin' '-v' '--no-fs' '--audio-spdif=ac3,dts-hd,truehd' '--vd-lavc-threads=4' '--hwdec=vaapi' '--sub-auto=fuzzy' '--vo=gpu,' '--audio-device=pulse/alsa_output.pci-0000_00_03.0.hdmi-stereo' '--ao=pulse,' '--no-input-default-bindings' '--input-vo-keyboard=no' '--no-input-cursor' '--cursor-autohide=no' '--no-keepaspect' '--wid=54525990' '--monitorpixelaspect=1' '--osd-level=0' '--osd-scale=1' '--osd-bar-align-y=0.6' '--sub-ass' '--embeddedfonts' '--sub-ass-line-spacing=0' '--sub-scale=1' '--sub-font=Arial' '--sub-color=#ffffffff' '--sub-shadow-color=#ff000000' '--sub-border-color=#ff000000' '--sub-border-size=0.75' '--sub-shadow-offset=2.5' '--sub-font-size=50' '--sub-bold=no' '--sub-italic=no' '--sub-codepage=ISO-8859-1' '--sub-pos=100' '--volume=40' '--cache=99999' '--screenshot-template=cap_%F_%p_%02n' '--screenshot-format=jpg' '--screenshot-directory=/tmp/smplayer_screenshots' '--volume-max=100' '--video-output-levels=auto' '--profile=gpu-hq' '--vo=gpu' '--opengl-swapinterval=1' '--video-sync=display-resample' '--audio-spdif=dts,ac3' '--audio-channels=2' '--ad=spdif:ac3,spdif:dts,' '--af=scaletempo,lavcac3enc=yes:640:3' '--script' '~/.config/mpv/scripts/xrandr.lua' '--term-playing-msg=MPV_VERSION=${=mpv-version:}
[debug] INFO_VIDEO_WIDTH=${=width}
[debug] INFO_VIDEO_HEIGHT=${=height}
[debug] INFO_VIDEO_ASPECT=${=video-aspect}
[debug] INFO_VIDEO_FPS=${=container-fps:${=fps}}
[debug] INFO_VIDEO_FORMAT=${=video-format}
[debug] INFO_VIDEO_CODEC=${=video-codec}
[debug] INFO_AUDIO_FORMAT=${=audio-codec-name}
[debug] INFO_AUDIO_CODEC=${=audio-codec}
[debug] INFO_AUDIO_RATE=${=audio-params/samplerate}
[debug] INFO_AUDIO_NCH=${=audio-params/channel-count}
[debug] INFO_LENGTH=${=duration:${=length}}
[debug] INFO_DEMUXER=${=current-demuxer:${=demuxer}}
[debug] INFO_SEEKABLE=${=seekable}
[debug] INFO_TITLES=${=disc-titles}
[debug] INFO_CHAPTERS=${=chapters}
[debug] INFO_TRACKS_COUNT=${=track-list/count}
[debug] METADATA_TITLE=${metadata/by-key/title:}
[debug] METADATA_ARTIST=${metadata/by-key/artist:}
[debug] METADATA_ALBUM=${metadata/by-key/album:}
[debug] METADATA_GENRE=${metadata/by-key/genre:}
[debug] METADATA_DATE=${metadata/by-key/date:}
[debug] METADATA_TRACK=${metadata/by-key/track:}
[debug] METADATA_COPYRIGHT=${metadata/by-key/copyright:}
[debug] INFO_MEDIA_TITLE=${=media-title:}
[debug] INFO_STREAM_PATH=${stream-path}
' '--audio-client-name=SMPlayer' '--term-status-msg=STATUS: ${=time-pos} / ${=duration:${=length:0}} P: ${=pause} B: ${=paused-for-cache} I: ${=core-idle} VB: ${=video-bitrate:0} AB: ${=audio-bitrate:0}' '/home/emba/Movies/Quiet Place, A.mkv'
mpv 0.29.1 Copyright © 2000-2018 mpv/MPlayer/mplayer2 projects
 built on Fri Oct  5 08:08:09 CEST 2018
ffmpeg library versions:
   libavutil       56.14.100
   libavcodec      58.18.100
   libavformat     58.12.100
   libswscale      5.1.100
   libavfilter     7.16.100
   libswresample   3.1.100
ffmpeg version: n4.0.2

Configuration: ./waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --enable-libsmbclient --enable-tv --enable-zsh-comp
List of enabled features: 52arch alsa asm atomics audio-input build-date caca cdda cplayer cplugins cuda-hwaccel debug-build drm drmprime dvbin dvdnav dvdread-common egl-drm egl-helpers egl-x11 fchmod ffmpeg ffnvcodec gbm gbm.h gl gl-wayland gl-x11 glibc-thread-name glob glob-posix gnuc gpl iconv jack jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libdl libm libmpv-shared librt libsmbclient libv4l2 linux-fstatfs lua optimize oss-audio plain-gl posix posix-or-mingw posix-spawn posix-spawn-native pthreads pulse rubberband stdatomic tv tv-v4l2 uchardet vaapi vaapi-drm vaapi-egl vaapi-glx vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vdpau-gl-x11 videodev vt.h vulkan wayland wayland-protocols x11 xv zlib zsh-comp
Waiting for scripts...
[input_file] Client connected
[ytdl_hook] script-opts/ytdl_hook.conf not found. 
[ytdl_hook] lua-settings/ytdl_hook.conf not found. 
[stats] script-opts/stats.conf not found. 
[stats] lua-settings/stats.conf not found. 
[osc] script-opts/osc.conf not found. 
[osc] lua-settings/osc.conf not found. 
Done loading scripts.
Playing: /home/emba/Movies/Quiet Place, A.mkv
Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[ifo] Opening /home/emba/Movies/Quiet Place, A.mkv
[ifo_dvdnav] Opening /home/emba/Movies/Quiet Place, A.mkv
[osd/libass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 2.0.2 (COMPLEX)
[osd/libass] Setting up fonts...
[bdmv/bluray] Opening /home/emba/Movies/Quiet Place, A.mkv
[file] Opening /home/emba/Movies/Quiet Place, A.mkv
[cache] Cache size set to 109999 KiB (10000 KiB backbuffer)
[demux] Trying demuxers for level=normal.
[mkv] Found the head...
[mkv] + a segment...
[mkv] Parsing seek head...
[mkv] |+ segment information...
[mkv] | + muxing app: libebml v1.3.6 + libmatroska v1.4.9
[mkv] | + writing app: mkvmerge v26.0.0 ('In The Game') 64-bit
[mkv] | + timecode scale: 1000000
[mkv] | + duration: 5414.880s
[mkv] | + segment uid a3 d7 d7 1b 39 f8 3e 63 7b 2e 45 61 ed 1c de f0
[mkv] |+ segment tracks...
[mkv] | + a track...
[mkv] |  + Track number: 1
[mkv] |  + Track type: Video
[mkv] |  + Video track
[mkv] |   + Display width: 1920
[mkv] |   + Display height: 800
[mkv] |   + Pixel width: 1920
[mkv] |   + Pixel height: 800
[mkv] |  + Codec ID: V_MPEG4/ISO/AVC
[mkv] |  + CodecPrivate, length 51
[mkv] |  + Language: und
[mkv] |  + Default duration: 41.708ms ( = 23.976 fps)
[mkv] | + a track...
[mkv] |  + Track number: 2
[mkv] |  + Track type: Audio
[mkv] |  + Audio track
[mkv] |   + Sampling frequency: 48000.000000
[mkv] |   + Channels: 6
[mkv] |  + Codec ID: A_AC3
[mkv] |  + Default duration: 32.000ms ( = 31.250 fps)
[mkv] | + a track...
[mkv] |  + Track number: 3
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_HDMV/PGS
[mkv] |  + Default flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 4
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_HDMV/PGS
[mkv] |  + Default flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 5
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_HDMV/PGS
[mkv] |  + Default flag: 0
[mkv] | + a track...
[mkv] |  + Track number: 6
[mkv] |  + Track type: Subtitle
[mkv] |  + Codec ID: S_HDMV/PGS
[mkv] |  + Default flag: 0
[mkv] Parsing attachments...
[mkv] Attachment: cover.jpg, image/jpeg, 253858 bytes
[mkv] Parsing chapters...
[mkv] New edition 0
[mkv] Default edition flag: 0
[mkv] Chapter 0 from 00:00:00.000 to 00:00:00.000, (01)00:00:00:000
[mkv] Chapter 1 from 00:10:19.160000000 to 00:00:00.000, (02)00:10:19:160
[mkv] Chapter 2 from 00:14:38.43000000 to 00:00:00.000, (03)00:14:38:043
[mkv] Chapter 3 from 00:21:52.936000000 to 00:00:00.000, (04)00:21:52:936
[mkv] Chapter 4 from 00:25:09.716000000 to 00:00:00.000, (05)00:25:09:716
[mkv] Chapter 5 from 00:31:05.196000000 to 00:00:00.000, (06)00:31:05:196
[mkv] Chapter 6 from 00:36:23.431000000 to 00:00:00.000, (07)00:36:23:431
[mkv] Chapter 7 from 00:43:47.333000000 to 00:00:00.000, (08)00:43:47:333
[mkv] Chapter 8 from 00:47:42.734000000 to 00:00:00.000, (09)00:47:42:734
[mkv] Chapter 9 from 00:53:48.225000000 to 00:00:00.000, (10)00:53:48:225
[mkv] Chapter 10 from 01:00:31.461000000 to 00:00:00.000, (11)01:00:31:461
[mkv] Chapter 11 from 01:05:55.409000000 to 00:00:00.000, (12)01:05:55:409
[mkv] Chapter 12 from 01:10:57.878000000 to 00:00:00.000, (13)01:10:57:878
[mkv] Chapter 13 from 01:15:29.149000000 to 00:00:00.000, (14)01:15:29:149
[mkv] Chapter 14 from 01:23:47.313000000 to 00:00:00.000, (15)01:23:47:313
[mkv] |+ found cluster
[mkv] Seeking to 6416357309 to read header element 0x1c53bb6b.
[cache] Dropping cache at pos 6416357309, cached range: 0-2752512.
[cache] Seeking underlying stream: 2752512 -> 6416357309
[mkv] Parsing cues...
[cache] EOF reached.
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[mkv] Seeking to 6416500628 to read header element 0x1254c367.
[cache] Dropping cache at pos 260833, cached range: 6416357309-6416502911.
[cache] Seeking underlying stream: 6416502911 -> 260833
[mkv] All headers are parsed!
[demux] Detected file format: Matroska
[cache] blocking for STREAM_CTRL 6
Opening done: /home/emba/Movies/Quiet Place, A.mkv
[find_files] Loading external files in /home/emba/Movies/
Running hook: ytdl_hook/on_preloaded
[mkv] select track 0
[mkv] select track 1
 (+) Video --vid=1 (*) (h264 1920x800 23.976fps)
     Video --vid=2 [P] 'cover.jpg' (mjpeg)
 (+) Audio --aid=1 --alang=eng (*) (ac3 6ch 48000Hz)
     Subs  --sid=1 --slang=eng (hdmv_pgs_subtitle)
     Subs  --sid=2 --slang=eng (hdmv_pgs_subtitle)
     Subs  --sid=3 --slang=eng (hdmv_pgs_subtitle)
     Subs  --sid=4 --slang=eng (hdmv_pgs_subtitle)
[display-tags] File tags:
[display-tags]  Title: Quiet Place, A
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'x11probe'
[vo/gpu/x11] X11 opening display: :0.0
[vo/gpu/x11] X11 running at 1920x1080 (":0.0" => local display)
[vo/gpu/x11] Display 0 (HDMI-1): [0, 0, 1920, 1080] @ 50.000000 FPS
[vo/gpu/x11] Current display FPS: 50.000000
[vo/gpu/opengl] GLX chose FB config with ID 0xba
[vo/gpu/opengl] GLX chose visual with ID 0x111
[vo/gpu/opengl] Creating OpenGL 4.4 context...
[vo/gpu] GL_VERSION='4.5 (Core Profile) Mesa 18.2.3'
[vo/gpu] Detected desktop OpenGL 4.5.
[vo/gpu] GL_VENDOR='Intel Open Source Technology Center'
[vo/gpu] GL_RENDERER='Mesa DRI Intel(R) Haswell Mobile '
[vo/gpu] GL_SHADING_LANGUAGE_VERSION='4.50'
[vo/gpu] Loaded extension GLX_SGI_swap_control.
[vo/gpu] Loaded extension GLX_MESA_swap_control.
[vo/gpu] Loaded extension GLX_SGI_video_sync.
[vo/gpu/opengl] No vdpau support found - probing more things.
[vo/gpu/x11] uninit ...
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0.0
[vo/gpu/x11] X11 running at 1920x1080 (":0.0" => local display)
[vo/gpu/x11] Display 0 (HDMI-1): [0, 0, 1920, 1080] @ 50.000000 FPS
[vo/gpu/x11] Current display FPS: 50.000000
[vo/gpu/opengl] EGL_VERSION=1.4 (DRI2)
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] chose visual 0x21
[vo/gpu/opengl] GL_VERSION='4.5 (Core Profile) Mesa 18.2.3'
[vo/gpu/opengl] Detected desktop OpenGL 4.5.
[vo/gpu/opengl] GL_VENDOR='Intel Open Source Technology Center'
[vo/gpu/opengl] GL_RENDERER='Mesa DRI Intel(R) Haswell Mobile '
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='4.50'
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Resize: 579x434
[vo/gpu] Reported display depth: 8
[vo/gpu] Assuming 50.000000 FPS for display sync.
[vd] Container reported FPS: 23.976025
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd]     h264_cuvid (h264) - Nvidia CUVID H264 decoder
[vd] Opening decoder h264
[vd] Looking at hwdec h264-vaapi...
[vo/gpu] Loading hwdec driver 'vaapi-egl'
[vo/gpu/vaapi-egl] Trying to open a x11 VA display...
[vo/gpu/vaapi-egl/vaapi] Initialized VAAPI: version 1.3
[vo/gpu/vaapi-egl] using VAAPI EGL interop
[vo/gpu/vaapi-egl] Supported formats:
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  yuv420p
[vo/gpu/vaapi-egl]  nv12
[vo/gpu/vaapi-egl]  yuv422p
[vo/gpu/vaapi-egl]  rgb0
[vo/gpu/vaapi-egl]  bgr0
[vo/gpu/vaapi-egl]  p010
[vo/gpu] Loading hwdec driver 'cuda-nvdec'
Cannot load libcuda.so.1
[vo/gpu/cuda-nvdec] Failed to load CUDA symbols
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'vdpau-glx'
[vo/gpu] Loading failed.
[vo/gpu] Loading hwdec driver 'drmprime-drm'
[vo/gpu/drmprime-drm] Failed to retrieve DRM fd from native display.
[vo/gpu] Loading failed.
[vd] Trying hardware decoding via h264-vaapi.
[vd] Pixel formats supported by decoder: vdpau cuda vaapi_vld yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'vaapi_vld' from decoder.
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     spdif_ac3 (ac3) - libavformat/spdifenc audio pass-through decoder
[ad] Opening decoder spdif_ac3
[ad] Selected codec: spdif_ac3 (libavformat/spdifenc audio pass-through decoder)
[af] User filter list:
[af]   scaletempo (scaletempo.00)
[af]   lavcac3enc (lavcac3enc.00)
Starting playback...
[ad] In: profile=-99 samplerate=0
[af] [in] 48000Hz stereo 2ch spdif-ac3
[af] [scaletempo] 48000Hz stereo 2ch spdif-ac3
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo spdif-ac3 -> 48000Hz stereo s16
[swresample] unsupported conversion: spdif-ac3 -> s16
[swresample] libswresample failed to initialize.
[af] Disabling filter scaletempo.00 because it has failed.
[af] [lavcac3enc] 48000Hz stereo 2ch spdif-ac3
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo spdif-ac3 -> 48000Hz stereo floatp
[swresample] unsupported conversion: spdif-ac3 -> floatp
[swresample] libswresample failed to initialize.
[af] Disabling filter lavcac3enc.00 because it has failed.
[af] [userspeed] 48000Hz stereo 2ch spdif-ac3
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch spdif-ac3
[vd] Pixel formats supported by decoder: vdpau cuda vaapi_vld yuv420p
[vd] Codec profile: High (0x64)
[vd] Requesting pixfmt 'vaapi_vld' from decoder.
[vd] Using hardware decoding (vaapi).
[vd] Decoder format: 1920x800 vaapi[nv12] auto/auto/auto/auto/auto CL=mpeg2/4/h264 (auto 0.000000/0.000000/0.000000)
[vd] Using container aspect ratio.
[vf] [in] 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[ao] Trying audio driver 'pulse'
[ao] Using preferred device 'alsa_output.pci-0000_00_03.0.hdmi-stereo'
[ao/pulse] requested format: 48000 Hz, stereo channels, spdif-ac3
[ao/pulse] Library version: 12.2.0
[ao/pulse] Proto: 32
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] Stream failed.
[ao] Trying audio driver 'pulse'
[ao] Using preferred device 'alsa_output.pci-0000_00_03.0.hdmi-stereo'
[ao/pulse] requested format: 48000 Hz, stereo channels, spdif-ac3
[xrandr] xrandr -q
[xrandr] Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 8192 x 8192
[xrandr] eDP-1 connected (normal left inverted right x axis y axis)
[xrandr]    1920x1080     60.01 +  60.01    59.97    59.96    59.93    40.00  
[xrandr]    1680x1050     59.95    59.88  
[xrandr]    1400x1050     59.98  
[xrandr]    1600x900      59.99    59.94    59.95    59.82  
[xrandr]    1280x1024     60.02  
[xrandr]    1400x900      59.96    59.88  
[xrandr]    1280x960      60.00  
[xrandr]    1440x810      60.00    59.97  
[xrandr]    1368x768      59.88    59.85  
[xrandr]    1280x800      59.99    59.97    59.81    59.91  
[xrandr]    1280x720      60.00    59.99    59.86    59.74  
[xrandr]    1024x768      60.04    60.00  
[xrandr]    960x720       60.00  
[xrandr]    928x696       60.05  
[xrandr]    896x672       60.01  
[xrandr]    1024x576      59.95    59.96    59.90    59.82  
[xrandr]    960x600       59.93    60.00  
[xrandr]    960x540       59.96    59.99    59.63    59.82  
[xrandr]    800x600       60.00    60.32    56.25  
[xrandr]    840x525       60.01    59.88  
[xrandr]    864x486       59.92    59.57  
[xrandr]    700x525       59.98  
[xrandr]    800x450       59.95    59.82  
[xrandr]    640x512       60.02  
[xrandr]    700x450       59.96    59.88  
[xrandr]    640x480       60.00    59.94  
[xrandr]    720x405       59.51    58.99  
[xrandr]    684x384       59.88    59.85  
[xrandr]    640x400       59.88    59.98  
[xrandr]    640x360       59.86    59.83    59.84    59.32  
[xrandr]    512x384       60.00  
[xrandr]    512x288       60.00    59.92  
[xrandr]    480x270       59.63    59.82  
[xrandr]    400x300       60.32    56.34  
[xrandr]    432x243       59.92    59.57  
[xrandr]    320x240       60.05  
[xrandr]    360x202       59.51    59.13  
[xrandr]    320x180       59.84    59.32  
[xrandr] VGA-1 disconnected (normal left inverted right x axis y axis)
[xrandr] DP-1 disconnected (normal left inverted right x axis y axis)
[xrandr] HDMI-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 698mm x 392mm
[xrandr]    1920x1080     50.00*+  60.00    60.00    50.00    59.94    24.00    23.98  
[xrandr]    1920x1080i    60.00    60.00    50.00    50.00    59.94  
[xrandr]    2880x576      50.00    50.00  
[xrandr]    2880x576i     50.00    50.00  
[xrandr]    2880x480      60.00    60.00    59.94    59.94  
[xrandr]    2880x480i     60.00    60.00    59.94    59.94  
[xrandr]    1280x720      60.00    50.00    50.00    59.94  
[xrandr]    1440x576      50.00    50.00  
[xrandr]    1440x480      60.00    60.00    59.94    59.94  
[xrandr]    720x576       50.00    50.00  
[xrandr]    720x576i      50.00    50.00  
[xrandr]    720x480       60.00    60.00    59.94    59.94  
[xrandr]    720x480i      60.00    60.00    59.94    59.94  
[xrandr]    640x480       60.00    59.94  
[xrandr] DP-2 disconnected (normal left inverted right x axis y axis)
[xrandr] HDMI-2 disconnected (normal left inverted right x axis y axis)
[xrandr]  
[xrandr] output eDP-1 mode=1920x1080 old rate=50.00 refresh rates =     50.00*+  60.00    60.00    50.00    59.94    24.00    23.98   
[xrandr] output HDMI-1 mode=1920x1080 old rate=50.00 refresh rates =     50.00*+  60.00    60.00    50.00    59.94    24.00    23.98   
[ao/pulse] Library version: 12.2.0
[ao/pulse] Proto: 32
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] Stream failed.
[ao] Trying audio driver 'alsa'
[ao/alsa] requested format: 48000 Hz, stereo channels, spdif-ac3
[ao/alsa] using ALSA version: 1.1.7
[ao/alsa] opening device 'default' => 'default:AES0=6,AES1=130,AES2=0,AES3=2'
ALSA lib conf.c:5001:(snd_config_expand) Unknown parameters AES0=6,AES1=130,AES2=0,AES3=2
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default:AES0=6,AES1=130,AES2=0,AES3=2
[ao/alsa] got error 'Invalid argument'; opening iec fallback device 'hdmi:AES0=6,AES1=130,AES2=0,AES3=2'
[ao/alsa] trying format s16/2
[ao/alsa] which we understand as: stereo
[ao/alsa] using spdif passthrough; ignoring the channel map.
[ao/alsa] hw pausing supported: yes
[ao/alsa] buffersize: 4800 samples
[ao/alsa] period size: 960 samples
[ao/alsa] device buffer: 4800 samples.
[ao/alsa] using soft-buffer of 10752 samples.
AO: [alsa] 48000Hz stereo 2ch spdif-ac3
AO: Description: ALSA audio output
[af] [convert] (disabled)
[af] [out] 48000Hz stereo 2ch spdif-ac3
VO: [gpu] 1920x800 vaapi[nv12]
VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1920x800 vaapi[nv12] bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu] Resize: 579x434
[vo/gpu] Window size: 579x434
[vo/gpu] Video source: 1920x800 (1:1)
[vo/gpu] Video display: (0, 0) 1920x800 -> (0, 0) 579x434
[vo/gpu] Video scale: 0.301563/0.542500
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Dither to 8.
[osd/libass] fontselect: (sans-serif, 400, 0) -> /usr/share/fonts/TTF/verdana.ttf, 0, Verdana
first video frame after restart shown
INFO_VIDEO_DSIZE=1920x800
[xrandr] no output is known to be used by mpv, assuming all connected outputs are used. 
[xrandr] container fps is 23.976024627686Hz, for output eDP-1 mode 1920x1080 the best fitting display fps rate is 23.976024627686Hz 
starting audio playback
[mkv] blocking on demuxer thread
[mkv] blocking for STREAM_CTRL 36
[cache] blocking for STREAM_CTRL 36
[mkv] blocking for DEMUXER_CTRL 4
MPV_VERSION=mpv 0.29.1
INFO_VIDEO_WIDTH=1920
INFO_VIDEO_HEIGHT=800
INFO_VIDEO_ASPECT=2.400000
INFO_VIDEO_FPS=23.976025
INFO_VIDEO_FORMAT=h264
INFO_VIDEO_CODEC=h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
INFO_AUDIO_FORMAT=ac3
INFO_AUDIO_CODEC=spdif_ac3 (libavformat/spdifenc audio pass-through decoder)
INFO_AUDIO_RATE=48000
INFO_AUDIO_NCH=2
INFO_LENGTH=5414.880000
INFO_DEMUXER=mkv
INFO_SEEKABLE=yes
INFO_TITLES=
INFO_CHAPTERS=15
INFO_TRACKS_COUNT=7
METADATA_TITLE=Quiet Place, A
METADATA_ARTIST=
METADATA_ALBUM=
METADATA_GENRE=
METADATA_DATE=
METADATA_TRACK=
METADATA_COPYRIGHT=
INFO_MEDIA_TITLE=Quiet Place, A
INFO_STREAM_PATH=/home/emba/Movies/Quiet Place, A.mkv

playback restart complete
[vo/gpu/x11] Disabling screensaver.
[vo/gpu] Resize: 1024x427
[vo/gpu] Window size: 1024x427
[vo/gpu] Video source: 1920x800 (1:1)
[vo/gpu] Video display: (0, 0) 1920x800 -> (0, 0) 1024x427
[vo/gpu] Video scale: 0.533333/0.533750
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8`

**Comment by lvml** [comment]
> Yesterday I changed the display in my Lenovo laptop from a 1600x900 to a FHD panel. [...]
> Now, whenever I open a file my laptop screen is lit up and the picture is mirrored on both screens.

Your output shows that you have two displays connected - one laptop-internal (eDP-1) and one external (HDMI-1).

Since mpv was not able to tell on which display(s) the video would play - see log line `[xrandr] no output is known to be used by mpv, assuming all connected outputs are used` - xrandr assumes "on both", and sets a mode for both displays.

If you want to have a picture only on the external HDMI display, you can try to insert
```
   dn = "HDMI-1"
```
at https://github.com/lvml/mpv-plugin-xrandr/blob/af6c335b2e61482c0deeed4226d55f0078927b96/xrandr.lua#L209 to assign a fixed list of outputs you want to use.

**Comment by lvml** [comment]
(Closing this issue as mpv-plugin-xrandr is moving to gitlab.com)
