### ISSUE TITLE
Back to the original frequency when MPV is closed

### ISSUE THREAD

**Issue by ghost** [lvml/mpv-plugin-xrandr#3]
Do the script can switch back to the original frequency if I close MPV or MPV close itself at the end of the video ?

Thank you.

**Comment by olm52** [comment]
This would  be very nice.

**Comment by lvml** [comment]
Could be possible - if what xrandr -q tells with its "*" behind the rate is true, and if mpv is willing to execute sort of an "exit" handler. Will have a look at that.

**Comment by olm52** [comment]
I have made a PKGBUILD for archlinux here
https://aur.archlinux.org/packages/mpv-plugin-xrandr/

Waiting for a different solution, I have added a simple script mpv.sh that will switch back to you original monitor configuration after playing is done.
The information about your  monitor is stored in /etc/mpv/default_screen.conf

#!/bin/bash
source /etc/mpv-plugin-xrandr/default_screen.conf
(mpv $1 --script /etc/mpv-plugin-xrandr/xrandr.lua; xrandr --output $OUTPUT --mode $MODE --rate $RATE)

**Comment by ghost** [comment]
Thank you for this (until it works "out of the box") !

**Comment by lvml** [comment]
Implemented enhancement in https://github.com/lvml/mpv-plugin-xrandr/commit/09366e1e322341f94ab85d26942ee2c965e267e0

**Comment by ghost** [comment]
Thank you very much ! Should we close this issue ?

**Comment by olm52** [comment]
For me yes. I have checked Paviluf enhancement and it is working.
I have also updated the arch package.
Thank you to all.
