### ISSUE TITLE
Problem with "hwdec=vdpau"

### ISSUE THREAD

**Issue by kalle-del-haye** [lvml/mpv-plugin-xrandr#4]
When using `vo=opengl` together with `hwdec=vdpau` your NVidia hack doesn’t work and I get this message:

```
[vo/opengl-hq/vdpau] Error when calling vdp_output_surface_create: An invalid handle value was provided.
[vo/opengl-hq] Initializing texture for hardware decoding failed.
[vo/opengl-hq] before video texture creation: OpenGL error INVALID_OPERATION.
[vo/opengl-hq/vdpau] Got display preemption notice! Will attempt to recover.
[vo/opengl-hq/vdpau] Recovered from display preemption.
[vo/opengl-hq/vdpau] Error when calling vdp_video_surface_get_parameters: An invalid handle value was provided.
[ffmpeg/video] h264: hardware accelerator failed to decode picture
Error while decoding frame!
[vo/opengl-hq/vdpau] Error when calling vdp_video_surface_get_parameters: An invalid handle value was provided.
```

So I extend the `if`-line in your lua script to:

```
if (mp.get_property("options/vo") == "vdpau" or mp.get_property("options/hwdec") == "vdpau") then
```

And the above error is gone.

But there is an other error on many (not all) video files, not sure if depending each other.

```
[xrandr]
[xrandr] stack traceback:
[xrandr]        [C]: in function 'commandv'
[xrandr]        /home/kodi/.config/mpv/scripts/xrandr.lua:271: in function 'prop'
[xrandr]        mp.defaults:360: in function 'handler'
[xrandr]        mp.defaults:436: in function 'call_event_handlers'
[xrandr]        mp.defaults:472: in function 'dispatch_events'
[xrandr]        mp.defaults:429: in function <mp.defaults:428>
[xrandr]        [C]: in ?
[xrandr]        [C]: in ?
[xrandr] Lua error: /home/kodi/.config/mpv/scripts/xrandr.lua:271: argument 2 is not a string
```

I'm using a nearly up to date `mpv git-7e285a6` from the ubuntu McMahon repository.
Maybe you can take a look on this problem. Thanks.

**Comment by lvml** [comment]
Thanks for your `... or mp.get_property("options/hwdec") == "vdpau"` idea, will use that.

Regarding the `Lua error: /home/kodi/.config/mpv/scripts/xrandr.lua:271: argument 2 is not a string`: I don't know how to reproduce this, but I'd guess your "vid" property is returned as "nil" in `old_vid = mp.get_property("vid")` at https://github.com/lvml/mpv-plugin-xrandr/blob/master/xrandr.lua#L216 - you can try replacing https://github.com/lvml/mpv-plugin-xrandr/blob/master/xrandr.lua#L269 with 

```
 if (old_vid ~= nil) then
    mp.set_property("vid", old_vid)
 end
```

If that helps it would be interesting to know why `get_property("vid")` returned nil for your video.

**Comment by kalle-del-haye** [comment]
Because I added a line in the script, the error pointed on the `old_position` line. Sorry.
I replaced that line with

```
if (old_position ~= nil) then
    mp.commandv("seek", old_position, "absolute", "keyframes")
else
    mp.msg.log("info", "ERROR old_position is 'nil'")
end
```

The error is gone and I just get this little message when `old_position` become nil.

So, the problem is the property `old_position`.
And it happened not only for one video but for almost all.

**Comment by lvml** [comment]
Great. Incorporated both changes with https://github.com/lvml/mpv-plugin-xrandr/commit/203097c02b69faebb70fafbdf4c0233fd8bce78c.
