### ISSUE TITLE
Don't turn on displays that are turned off.

### ISSUE THREAD

**Issue by perlop** [lvml/mpv-plugin-xrandr#5]
I have a laptop and I plug it to the tv. I also have this plugin installed with mpv. When I open a video this plugin turns on the laptop's display. when I have it turned off. I want to have the TV's display open only.

Is there an option for that? Or is it something that can be fixed.

**Comment by lvml** [comment]
xrandr.lua tries to "touch" only display outputs that mpv is reporting as "being used" for the video playback, but mpv in turn relies on the graphics driver to supply that information, and not all graphics drivers provide it. Without information on which display outputs are used, xrandr.lua currently has no other option than to set the refresh rate on all of them, and that might indeed turn on a formerly turned-off output.

How do you turn off the display of your laptop? Using a function key?

Please provide the output of "xrandr" (when just invoked without arguments from the command line), before and after the "unintended laptop display turn-on".

Also, what kind of GPU are you using (Intel, nvidia, AMD, ...)?

Should there be no way to automatically detect "turned off" display outputs, maybe a blacklist option could be implemented as a workaround.

**Comment by perlop** [comment]
Hi. I use a custom script to have only one video output so when HDMI is connected I turn only that on nad turn off the laptop's display and vice versa. It uses xrandr commands. I use an amd GPU.

```
[user@localhost ~] $ lspci
...
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Wrestler [Radeon HD 6310]
...
```

Here is the xrandr output.
BEFORE

```
[vaio@localhost ~] $ xrandr
Screen 0: minimum 320 x 200, current 1280 x 720, maximum 8192 x 8192
LVDS connected (normal left inverted right x axis y axis)
   1366x768      59.97 +
   1280x720      59.86  
   1152x768      59.78  
   1024x768      60.04    60.00    59.92  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   800x600       60.00    60.32    59.86    56.25  
   848x480       59.66  
   700x525       59.98  
   720x480       59.71  
   640x512       60.02  
   640x480       60.00    59.94    59.38  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
HDMI-0 connected primary 1280x720+0+0 (normal left inverted right x axis y axis) 1107mm x 623mm
   1920x1080     60.00 +  50.00    59.94    30.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x720      60.00*   50.00    30.00    59.94    29.97    24.00    23.98  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       60.00    59.94  
VGA-0 disconnected (normal left inverted right x axis y axis)
```

AFTER

```
[vaio@localhost ~] $ xrandr
Screen 0: minimum 320 x 200, current 1280 x 720, maximum 8192 x 8192
LVDS connected 1280x720+0+0 (normal left inverted right x axis y axis) 256mm x 144mm
   1366x768      59.97 +
   1280x720      59.86* 
   1152x768      59.78  
   1024x768      60.04    60.00    59.92  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   800x600       60.00    60.32    59.86    56.25  
   848x480       59.66  
   700x525       59.98  
   720x480       59.71  
   640x512       60.02  
   640x480       60.00    59.94    59.38  
   512x384       60.00  
   400x300       60.32    56.34  
   320x240       60.05  
HDMI-0 connected primary 1280x720+0+0 (normal left inverted right x axis y axis) 1107mm x 623mm
   1920x1080     60.00 +  50.00    59.94    30.00    24.00    29.97    23.98  
   1920x1080i    60.00    50.00    59.94  
   1600x900      60.00  
   1280x1024     60.02  
   1280x720      60.00    50.00*   30.00    59.94    29.97    24.00    23.98  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x576i      50.00  
   720x480       60.00    59.94  
   720x480i      60.00    59.94  
   640x480       60.00    59.94  
VGA-0 disconnected (normal left inverted right x axis y axis)
```

Maybe the script can use the asterisk(*) to detect the turned-on displays?
Also even though it says LVDS connected the laptop's display is turned off.

**Comment by lvml** [comment]
Ok, I've comitted a change to address this: https://github.com/lvml/mpv-plugin-xrandr/commit/984406a6092395ad83a8cb7f8fdd59bf0e0fe68b
Please try it and tell us whether that works for you.

**Comment by perlop** [comment]
Thank you! It works as expected. I am closing this as I find the issue to be resolved.
