### ISSUE TITLE
Will not use an appropriate user-defined mode

### ISSUE THREAD

**Issue by stseelig** [lvml/mpv-plugin-xrandr#7]
I added a 48hz mode to my monitors with the help of cvt.

> $ cvt 3840 2160 47.952
> # 3840x2160 47.94 Hz (CVT) hsync: 106.53 kHz; pclk: 560.75 MHz
> Modeline "3840x2160_47.95"  560.75  3840 4136 4552 5264  2160 2163 2168 2222 -hsync +vsync
> $ xrandr --newmode "3840x2160_47.95"  560.75  3840 4136 4552 5264  2160 2163 2168 2222 -hsync +vsync
> $ xrandr --addmode DisplayPort-0 "3840x2160_47.95"
> $ xrandr --addmode DisplayPort-1 "3840x2160_47.95"

my xrandr output now looks like

> Screen 0: minimum 320 x 200, current 6000 x 3840, maximum 16384 x 16384
> DisplayPort-0 connected primary 3840x2160+2160+840 (normal left inverted right x axis y axis) 521mm x 293mm
>   3840x2160     60.00_+
>   2560x1440     59.95
>   1920x1080     60.00    60.00    59.94
>   1920x1080i    60.00    59.94
>   1280x1024     60.02
>   1280x960      60.00
>   1280x720      60.00    59.94
>   1024x768      60.00
>   1440x480      60.00    59.94
>   832x624       74.55
>   800x600       60.32
>   720x480       60.00    59.94
>   640x480       60.00    59.94
>   720x400       70.08
>   640x350       70.10
>   3840x2160_47.95  47.94
> DisplayPort-1 connected 2160x3840+0+0 left (normal left inverted right x axis y axis) 521mm x 293mm
>   3840x2160     60.00_+
>   2560x1440     59.95
>   1920x1080     60.00    60.00    59.94
>   1920x1080i    60.00    59.94
>   1280x1024     60.02
>   1280x960      60.00
>   1280x720      60.00    59.94
>   1024x768      60.00
>   1440x480      60.00    59.94
>   832x624       74.55
>   800x600       60.32
>   720x480       60.00    59.94
>   640x480       60.00    59.94
>   720x400       70.08
>   640x350       70.10
>   3840x2160_47.95  47.94
> DisplayPort-2 disconnected (normal left inverted right x axis y axis)
> HDMI-A-0 disconnected (normal left inverted right x axis y axis)
> DVI-D-0 disconnected (normal left inverted right x axis y axis)

When playing a 23.976 fps video, the script sets the monitor to 60Hz. In the below example, my monitor was at 48hz.

> [xrandr] output DisplayPort-0 mode=3840x2160 old rate=60.00 refresh rates =     60.00_+
> [xrandr] output DisplayPort-1 mode=3840x2160 old rate=60.00 refresh rates =     60.00_+
> [xrandr] container fps is 23.976024627686Hz, for output DisplayPort-0 mode 3840x2160 the best fitting display fps rate is 60Hz

**Comment by lvml** [comment]
> I added a 48hz mode to my monitors with the help of cvt.
> 
> ```
> $ cvt 3840 2160 47.952
> # 3840x2160 47.94 Hz (CVT) hsync: 106.53 kHz; pclk: 560.75 MHz
> Modeline "3840x2160_47.95" 560.75 3840 4136 4552 5264 2160 2163 2168 2222 -hsync +vsync
> $ xrandr --newmode "3840x2160_47.95" 560.75 3840 4136 4552 5264 2160 2163 2168 2222 -hsync +vsync
> $ xrandr --addmode DisplayPort-0 "3840x2160_47.95"
> $ xrandr --addmode DisplayPort-1 "3840x2160_47.95"
> ```

Did you (outside of mpv) verify that this new mode works fine on your displays? As in...

```
 xrandr --output DisplayPort-0 --mode "3840x2160_47.95"
 xrandr --output DisplayPort-1 --mode "3840x2160_47.95"
```

(It would not be unlikely for a display to not work with such a rate... and if
it doesn't, attempts to have mpv-plugin-xrandr switch to it would be futile.)

> my xrandr output now looks like
>     Screen 0: minimum 320 x 200, current 6000 x 3840, maximum 16384 x 16384
>     DisplayPort-0 connected primary 3840x2160+2160+840 (normal left inverted right x axis y axis) 521mm x 293mm
>     3840x2160 60.00/+
> ...
>     3840x2160_47.95 47.94

Given this output from xrandr, mpv-plugin-xrandr would necessarily assume
that "3840x2160" (and not "3840x2160_47.95") is the mode to use.
(You created a whole new mode, not just another refresh-rate for an existing
mode.)

You could try the recently introduced option

```
 --script-opts=xrandr-output-mode=3840x2160_47.95
```

to make mpv-plugin-xrandr explicitely switch to this particular mode
while mpv runs.

There are currently regular expressions in xrandr.lua that assume
the name of the mode consists of digits and "x", only. I can
extend them to include letters like "_" and ".", but that's only
relevant to make the mode in question automatically detected
when it is active at the time mpv is started.

> When playing a 23.976 fps video, the script sets the monitor to 60Hz. In the below example, my
> monitor was at 48hz.
> 
> ```
> [xrandr] output DisplayPort-0 mode=3840x2160 old rate=60.00 refresh rates = 60.00/+
> [xrandr] output DisplayPort-1 mode=3840x2160 old rate=60.00 refresh rates = 60.00/+
> [xrandr] container fps is 23.976024627686Hz, for output DisplayPort-0 mode 3840x2160 the best
> fitting display fps rate is 60Hz
> ```

This could be explained by the non-match of the regular expressions, if
in fact your output was using 48Hz at that time (and should have, unlike
in the xrandr output quoted above, displayed an asterisk after the
"3840x2160_47.95 47.94").

You could try whether your setting works if you just use a different
name for your mode, like "3840x2160x48", for testing purposes.

**Comment by stseelig** [comment]
> Did you (outside of mpv) verify that this new mode works fine on your displays?

Yes, my monitor's OSD says that it is running at 48Hz.
![hni_0034](https://cloud.githubusercontent.com/assets/20758242/17304994/4da6c736-57f6-11e6-8a0d-0fd9b6104084.JPG)

> unlike in the xrandr output quoted above, displayed an asterisk after the "3840x2160_47.95 47.94").

It was working, I just messed up the copy-paste. (I removed blank characters at the end of every line that were messing up the formatting, and accidently removed the '*'.)

> You could try whether your setting works if you just use a different name for your mode, like "3840x2160x48", for testing purposes.

I did that. Now, if the video is 24Hz decimated, it will not switch to 60Hz if it is running at 48Hz. But  it will not switch to 48Hz if it is running at 60Hz.

> [xrandr] output DisplayPort-0 mode=3840x2160x48 old rate=47.94 refresh rates =  47.94*
> [xrandr] output DisplayPort-1 mode=3840x2160 old rate=60.00 refresh rates =     60.00*+
> [xrandr] container fps is 23.976024627686Hz, for output DisplayPort-0 mode 3840x2160x48 the best fitting display fps rate is 47.94Hz
> 
> [xrandr] output DisplayPort-0 mode=3840x2160 old rate=60.00 refresh rates =     60.00_+
> [xrandr] output DisplayPort-1 mode=3840x2160 old rate=60.00 refresh rates =     60.00_+
> [xrandr] container fps is 23.976024627686Hz, for output DisplayPort-0 mode 3840x2160 the best fitting display fps rate is 60Hz

It does the same thing even if both of my monitors are at 48Hz.

current xrandr output

> Screen 0: minimum 320 x 200, current 6000 x 3840, maximum 16384 x 16384
> DisplayPort-0 connected primary 3840x2160+2160+840 (normal left inverted right x axis y axis) 521mm x 293mm
>    3840x2160     60.00 +
>    2560x1440     59.95
>    1920x1080     60.00    60.00    59.94
>    1920x1080i    60.00    59.94
>    1280x1024     60.02
>    1280x960      60.00
>    1280x720      60.00    59.94
>    1024x768      60.00
>    1440x480      60.00    59.94
>    832x624       74.55
>    800x600       60.32
>    720x480       60.00    59.94
>    640x480       60.00    59.94
>    720x400       70.08
>    640x350       70.10
>    3840x2160x48  47.94*
> DisplayPort-1 connected 2160x3840+0+0 left (normal left inverted right x axis y axis) 521mm x 293mm
>    3840x2160     60.00*+
>    2560x1440     59.95
>    1920x1080     60.00    60.00    59.94
>    1920x1080i    60.00    59.94
>    1280x1024     60.02
>    1280x960      60.00
>    1280x720      60.00    59.94
>    1024x768      60.00
>    1440x480      60.00    59.94
>    832x624       74.55
>    800x600       60.32
>    720x480       60.00    59.94
>    640x480       60.00    59.94
>    720x400       70.08
>    640x350       70.10
>    3840x2160x48  47.94
> DisplayPort-2 disconnected (normal left inverted right x axis y axis)
> HDMI-A-0 disconnected (normal left inverted right x axis y axis)
> DVI-D-0 disconnected (normal left inverted right x axis y axis)

**Comment by stseelig** [comment]
I was able to fix this by adding new modelines to my xorg.conf

> Section "Module"
>     Load  "glx"
> EndSection
> 
> Section "Device"
>     Option      "TearFree" "on"
>     Identifier  "Card0"
>     Driver      "amdgpu"
>     BusID       "PCI:1:0:0"
> EndSection
> 
> Section "Monitor"
>     Identifier  "DisplayPort-0"
>       Modeline "3840x2160"  587.00  3840 4144 4560 5280  2160 2163 2168 2225 -hsync +vsync
>       Modeline "3840x2160"  560.75  3840 4136 4552 5264  2160 2163 2168 2222 -hsync +vsync
> EndSection
> 
> Section "Monitor"
>     Identifier   "DisplayPort-1"
>       Modeline "3840x2160"  587.00  3840 4144 4560 5280  2160 2163 2168 2225 -hsync +vsync
>       Modeline "3840x2160"  560.75  3840 4136 4552 5264  2160 2163 2168 2222 -hsync +vsync
> EndSection
> 
> Section "Screen"
>     Identifier  "Screen0"
>     Device      "Card0"
>     Monitor     "DisplayPort-0"
>     Monitor     "DisplayPort-1"
>     DefaultDepth 24
>     SubSection "Display"
>         Depth     24
>     EndSubSection
> EndSection

xrandr

> Screen 0: minimum 320 x 200, current 6000 x 3840, maximum 16384 x 16384
> DisplayPort-0 connected primary 3840x2160+2160+840 (normal left inverted right x axis y axis) 521mm x 293mm
>    3840x2160     60.00_\+  49.97    47.94
>    2560x1440     59.95
>    1920x1080     60.00    60.00    59.94
>    1920x1080i    60.00    59.94
>    1280x1024     60.02
>    1280x960      60.00
>    1280x720      60.00    59.94
>    1024x768      60.00
>    1440x480      60.00    59.94
>    832x624       74.55
>    800x600       60.32
>    720x480       60.00    59.94
>    640x480       60.00    59.94
>    720x400       70.08
>    640x350       70.10
> DisplayPort-1 connected 2160x3840+0+0 left (normal left inverted right x axis y axis) 521mm x 293mm
>    3840x2160     60.00_\+  49.97    47.94
>    2560x1440     59.95
>    1920x1080     60.00    60.00    59.94
>    1920x1080i    60.00    59.94
>    1280x1024     60.02
>    1280x960      60.00
>    1280x720      60.00    59.94
>    1024x768      60.00
>    1440x480      60.00    59.94
>    832x624       74.55
>    800x600       60.32
>    720x480       60.00    59.94
>    640x480       60.00    59.94
>    720x400       70.08
>    640x350       70.10
> DisplayPort-2 disconnected (normal left inverted right x axis y axis)
> HDMI-A-0 disconnected (normal left inverted right x axis y axis)
> DVI-D-0 disconnected (normal left inverted right x axis y axis)

xrandr doesn't seem to be able to add new modes to existing names

**Comment by lvml** [comment]
> xrandr doesn't seem to be able to add new modes to existing names

Yes, and therefore I think you did the right thing to add Modelines to your xorg.conf, it's the better solution than us trying to somehow make xrandr.lua use different modes with different names for different refresh rates.
