### ISSUE TITLE
It doesn't change the refresh rate of my screen.

### ISSUE THREAD

**Issue by JulianLai** [lvml/mpv-plugin-xrandr#9]
[xrandr] output HDMI1 mode=1920x1080 old rate=60.00 refresh rates =     60.00*+  50.00    59.94  
[xrandr] container fps is 23.976024627686Hz, for output HDMI1 mode 1920x1080 the best fitting display fps rate is 60Hz 

Shouldn't it be 48 or 72 hz? Why still 60?

**Comment by lvml** [comment]
According to the output you provided
`[xrandr] output HDMI1 mode=1920x1080 old rate=60.00 refresh rates = 60.00*+ 50.00 59.94`
there is no 48Hz or 72Hz mode available for your display on output HDMI1.

Have you tried to switch your display to 48Hz or 72Hz output directly, invoking the xandr executable? That shouldn't work, either, but tell us if it does.

If you have reason to believe that your display should support refresh rates other than the ones xrandr reports, you could try defining additional "ModeLine"s in your xorg.conf, as this user did: https://github.com/lvml/mpv-plugin-xrandr/issues/7#issuecomment-236717892
